server:
  port: 8443
  ssl:
    protocol: TLS
    key-store-type: JKS
    key-store: classpath:.keystore
    key-store-password: javastack

spring:
  messages:
    basename: i18n/common, i18n/index
    fallback-to-system-locale: false
  security:
    user:
      name: root
      password: root
#  可添加到全局配置文件中
#  devtools:
#    restart:
#      log-condition-evaluation-delta: false
#      trigger-file: ".reloadtrigger"