spring:
  application:
    name: spring-boot-actuator

server:
  port: 8080

management:
#  server:
#    port: 8088
#    address: 127.0.0.1
  endpoints:
    jmx:
      exposure:
        include: health,info
    web:
      discovery:
        enabled: true
      base-path: /actuator
      path-mapping:
        health: health
      exposure:
        include: "*"
        exclude: threaddump
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,POST"
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true